package POJO;
// Generated May 26, 2020 3:19:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hocsinh generated by hbm2java
 */
public class Hocsinh  implements java.io.Serializable {


     private int maSv;
     private String hoTen;
     private Date ngaySinh;
     private String diaChi;

    public Hocsinh() {
    }

	
    public Hocsinh(int maSv) {
        this.maSv = maSv;
    }
    public Hocsinh(int maSv, String hoTen, Date ngaySinh, String diaChi) {
       this.maSv = maSv;
       this.hoTen = hoTen;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
    }
   
    public int getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(int maSv) {
        this.maSv = maSv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }




}


